# common configurations to source
NAME="defl"
ODOO_PATH="$HOME/GitHub/odoo"
TICKETS_FOLDER="tickets"
BASES_FOLDER="tickets"

# related paths
WORKSPACE_PATH="$ODOO_PATH/odoo.code-workspace"
ODOO_OC_PATH="$ODOO_PATH/odoo"
ODOO_OE_PATH="$ODOO_PATH/enterprise"
TICKETS_PATH="$ODOO_PATH/$TICKETS_FOLDER"
BASES_PATH="$ODOO_PATH/$BASES_FOLDER"

FILESTORE_PATH="$HOME/odoo/.local/share/Odoo/filestore"

log() {
    echo "[BFF] $*"
}
